{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}-token
  namespace: {{ .Release.Namespace }}
stringData:
  token: {{ .Values.externalSecrets.vault.token | quote }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.server | quote }}
      path: {{ .Values.externalSecrets.vault.path | quote }}
      version: {{ .Values.externalSecrets.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.externalSecrets.secretStoreName }}-token
          key: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.externalSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.database.secretName }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.externalSecrets.remoteKey | quote }}
      property: username
  - secretKey: password
    remoteRef:
      key: {{ .Values.externalSecrets.remoteKey | quote }}
      property: password
{{- end }}
