apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-creds-sync
  namespace: student-api
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: db-creds-final
  data:
  - secretKey: username
    remoteRef:
      key: secret/student-api/db-creds
      property: username
  - secretKey: password
    remoteRef:
      key: secret/student-api/db-creds
      property: password
