apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/rahul98076/student-api.git
    targetRevision: ci-updates
    path: helm/external-secrets
    helm:
      values: |
        installCRDs: false
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  resources:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    invert: true