apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-postgres-exporter
    targetRevision: 15.0.0
    helm:
      values: |
        serviceMonitor:
          enabled: true
          namespace: observability
          interval: 30s
        config:
          datasource:
            host: postgres-db-postgresql.student-api.svc.cluster.local
            port: 5432
            user: postgres
            password: studentpass
            database: studentdb
        nodeSelector:
          type: dependent_services
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
