apiVersion: v2
name: vault
description: Official HashiCorp Vault Chart
type: application
version: 1.0.0
appVersion: "1.18.2"

dependencies:
  - name: vault
    version: "0.32.0"
    repository: "https://helm.releases.hashicorp.com"
