apiVersion: v2
name: observability
description: Observability stack (Prometheus, Loki, Grafana, exporters)
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: ">=0.0.0-0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki
    version: ">=0.0.0-0"
    repository: "https://grafana.github.io/helm-charts"
  - name: promtail
    version: ">=0.0.0-0"
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus-blackbox-exporter
    version: ">=0.0.0-0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: prometheus-postgres-exporter
    version: ">=0.0.0-0"
    repository: "https://prometheus-community.github.io/helm-charts"
