replicaCount: 1

image:
  repository: rahul98076/student-api
  tag: "2c74b28"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 5000
  nodePort: 30001

database:
  host: "postgres-db-postgresql"
  port: "5432"
  name: "studentdb"
  secretName: "db-creds-final"

externalSecrets:
  enabled: true
  vault:
    server: "http://vault.vault.svc.cluster.local:8200"
    path: "secret"
    version: "v2"
    token: "root"
  secretStoreName: "vault-backend"
  externalSecretName: "db-creds-sync"
  remoteKey: "secret/student-api/db-creds"

nodeSelector:
  type: application
