apiVersion: v2
name: postgres
description: A community-managed Postgres chart
type: application
version: 1.0.0
appVersion: "16.0.0"

dependencies:
  - name: postgresql
    version: "16.5.5"
    repository: "https://charts.bitnami.com/bitnami"
