apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-api
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "studentdb"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application


      initContainers:
      - name: run-migrations
        image: rahul98076/student-api:v1
        imagePullPolicy: Always
        command: ["flask", "db", "upgrade"]
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds-final
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds-final
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: DB_HOST
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"

      containers:
      - name: student-api
        image: rahul98076/student-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-creds-final
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds-final
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: student-api-config
              key: DB_HOST
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"

---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
  - port: 8080
    targetPort: 5000
    nodePort: 30001
