apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
patchesStrategicMerge:
  - patches/argocd-application-controller.yaml
  - patches/argocd-applicationset-controller.yaml
  - patches/argocd-dex-server.yaml
  - patches/argocd-notifications-controller.yaml
  - patches/argocd-redis.yaml
  - patches/argocd-repo-server.yaml
  - patches/argocd-server.yaml
