apiVersion: v2
name: external-secrets-wrapper
description: Helm chart for External Secrets Operator
type: application
version: 1.0.0
appVersion: "0.9.0"

dependencies:
  - name: external-secrets
    version: "0.9.x"
    repository: "https://charts.external-secrets.io"
