name: CI Pipeline
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "helm/**"
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: self-hosted
    env:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      DATABASE_URL: "sqlite:///:memory:"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          make venv
          . venv/bin/activate
          make install

      - name: Lint Code
        run: |
          . venv/bin/activate
          make lint

      - name: Run Tests
        run: |
          . venv/bin/activate
          make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          make build VERSION=${{ env.SHORT_SHA }}
          make push VERSION=${{ env.SHORT_SHA }}

      - name: Update Helm Chart & Deploy
        run: |
          sed -i 's/tag: .*/tag: "${{ env.SHORT_SHA }}"/' helm/student-api/values.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add helm/student-api/values.yaml
          git commit -m "Deploy: Update image tag to ${{ env.SHORT_SHA }}"
          git push origin main
