name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - migrations/**
      - tests/**
      - run.py
      - requirements.txt
      - Dockerfile
      - Makefile
      - .github/workflows/ci.yml
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: self-hosted
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    env:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      DATABASE_URL: "sqlite:///:memory:"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          make venv
          . venv/bin/activate
          make install

      - name: Lint Code
        run: |
          . venv/bin/activate
          make lint

      - name: Run Tests
        run: |
          . venv/bin/activate
          make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: image_tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and Push
        run: |
          make build VERSION=${{ steps.image_tag.outputs.tag }}
          make push VERSION=${{ steps.image_tag.outputs.tag }}

      - name: Update Helm Chart & Deploy
        if: github.ref_type != 'tag'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git pull --rebase origin main 

          sed -i 's/tag: .*/tag: "${{ steps.image_tag.outputs.tag }}"/' helm/student-api/values.yaml

          git add helm/student-api/values.yaml

          git commit -m "Deploy: Update image tag to ${{ steps.image_tag.outputs.tag }} [skip ci]"
          git push origin main