name: CI Pipeline

on:
  push:
    tags:
      - "v*.*.*" 
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: self-hosted
    env:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      DATABASE_URL: "sqlite:///:memory:"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          make venv
          . venv/bin/activate
          make install

      - name: Lint Code
        run: |
          . venv/bin/activate
          make lint

      - name: Run Tests
        run: |
          . venv/bin/activate
          make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          make build VERSION=${{ github.ref_name }}
          make push VERSION=${{ github.ref_name }}

      - name: Update Helm Chart & Deploy
        run: |
          sed -i 's/tag: .*/tag: "${{ github.ref_name }}"/' helm/student-api/values.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git pull --rebase origin main 
          git add helm/student-api/values.yaml
          

          git commit -m "Deploy: Update image tag to ${{ github.ref_name }} [skip ci]"
          git push origin main